server:
    port: 8080

# License相关配置
license:
    subject: license_demo
    publicAlias: publicCert
    storePass: public_password1234
    licensePath: /usr/local/bin/test/license.lic
    publicKeysStorePath: /usr/local/bin/test/publicCerts.keystore
