server:
    servlet:
        context-path: /mobile
    tomcat:
        threads:
            max: 1000 # 最大线程数（默认200）
        max-connections: 10000 # 最大连接数（并发量）

spring:
    profiles:
        active: dev

    jackson:
        time-zone: GMT+8
        default-property-inclusion: non_null

    servlet:
        multipart:
            max-file-size: 1024MB
            max-request-size: 1024MB
