server:
    port: 8080

# License相关配置
license:
    subject: license_demo
    publicAlias: publicCert
    storePass: public_password1234
    licensePath: C:/Users/Administrator/Desktop/test/license.lic
    publicKeysStorePath: C:/Users/Administrator/Desktop/test/publicCerts.keystore
